import { daysAgo } from "./id.util";
import { MockInventoryRecord } from "./types";

/** Stock records for the admin "Inventory" screen — becomes central once the platform moves into Phase 2 (own-stock), per PRD. */
export const INVENTORY: MockInventoryRecord[] = [
  {
    id: "inv_001",
    sku: "SVN-HOOD-CLD-S",
    productName: "V2 Hoodie — Cloud",
    variantLabel: "Size S",
    warehouseLocation: "Lahore Warehouse — Rack A3",
    stockQty: 4,
    lowStockThreshold: 15,
    lastRestockedAt: daysAgo(18),
    movements: [
      { id: "mv_001", type: "in", quantity: 40, reason: "VOL. 07 initial stock", occurredAt: daysAgo(18) },
      { id: "mv_002", type: "out", quantity: 36, reason: "Orders fulfilled", occurredAt: daysAgo(2) },
    ],
  },
  {
    id: "inv_002",
    sku: "SVN-HOOD-CLD-M",
    productName: "V2 Hoodie — Cloud",
    variantLabel: "Size M",
    warehouseLocation: "Lahore Warehouse — Rack A3",
    stockQty: 42,
    lowStockThreshold: 15,
    lastRestockedAt: daysAgo(6),
    movements: [
      { id: "mv_003", type: "in", quantity: 60, reason: "VOL. 07 restock", occurredAt: daysAgo(6) },
      { id: "mv_004", type: "out", quantity: 18, reason: "Orders fulfilled", occurredAt: daysAgo(1) },
    ],
  },
  {
    id: "inv_003",
    sku: "SVN-HOOD-CLD-L",
    productName: "V2 Hoodie — Cloud",
    variantLabel: "Size L",
    warehouseLocation: "Lahore Warehouse — Rack A3",
    stockQty: 27,
    lowStockThreshold: 15,
    lastRestockedAt: daysAgo(6),
    movements: [{ id: "mv_005", type: "in", quantity: 60, reason: "VOL. 07 restock", occurredAt: daysAgo(6) }],
  },
  {
    id: "inv_004",
    sku: "SVN-TEE-CHR-M",
    productName: "Overdye Tee — Charcoal",
    variantLabel: "Size M",
    warehouseLocation: "Lahore Warehouse — Rack B1",
    stockQty: 61,
    lowStockThreshold: 20,
    lastRestockedAt: daysAgo(10),
    movements: [
      { id: "mv_006", type: "in", quantity: 80, reason: "Restock", occurredAt: daysAgo(10) },
      { id: "mv_007", type: "out", quantity: 19, reason: "Orders fulfilled", occurredAt: daysAgo(4) },
    ],
  },
  {
    id: "inv_005",
    sku: "SVN-TEE-CHR-L",
    productName: "Overdye Tee — Charcoal",
    variantLabel: "Size L",
    warehouseLocation: "Lahore Warehouse — Rack B1",
    stockQty: 9,
    lowStockThreshold: 20,
    lastRestockedAt: daysAgo(25),
    movements: [
      { id: "mv_008", type: "in", quantity: 50, reason: "Restock", occurredAt: daysAgo(25) },
      { id: "mv_009", type: "out", quantity: 41, reason: "Orders fulfilled", occurredAt: daysAgo(3) },
    ],
  },
  {
    id: "inv_006",
    sku: "SVN-CRGO-OLV-32",
    productName: "Cargo Pant — Olive",
    variantLabel: "Waist 32",
    warehouseLocation: "Karachi Warehouse — Rack C2",
    stockQty: 33,
    lowStockThreshold: 12,
    lastRestockedAt: daysAgo(14),
    movements: [{ id: "mv_010", type: "in", quantity: 45, reason: "Restock", occurredAt: daysAgo(14) }],
  },
  {
    id: "inv_007",
    sku: "SVN-CRGO-OLV-34",
    productName: "Cargo Pant — Olive",
    variantLabel: "Waist 34",
    warehouseLocation: "Karachi Warehouse — Rack C2",
    stockQty: 7,
    lowStockThreshold: 12,
    lastRestockedAt: daysAgo(30),
    movements: [
      { id: "mv_011", type: "in", quantity: 30, reason: "Restock", occurredAt: daysAgo(30) },
      { id: "mv_012", type: "out", quantity: 23, reason: "Orders fulfilled", occurredAt: daysAgo(5) },
    ],
  },
  {
    id: "inv_008",
    sku: "SVN-COACH-INK-M",
    productName: "Coach Jacket — Ink",
    variantLabel: "Size M",
    warehouseLocation: "Lahore Warehouse — Rack A1",
    stockQty: 16,
    lowStockThreshold: 10,
    lastRestockedAt: daysAgo(20),
    movements: [{ id: "mv_013", type: "in", quantity: 25, reason: "Restock", occurredAt: daysAgo(20) }],
  },
  {
    id: "inv_009",
    sku: "SVN-BEAN-BLK-OS",
    productName: "Ribbed Beanie — Black",
    variantLabel: "One Size",
    warehouseLocation: "Lahore Warehouse — Rack D4",
    stockQty: 5,
    lowStockThreshold: 20,
    lastRestockedAt: daysAgo(45),
    movements: [
      { id: "mv_014", type: "in", quantity: 60, reason: "Restock", occurredAt: daysAgo(45) },
      { id: "mv_015", type: "out", quantity: 55, reason: "Orders fulfilled", occurredAt: daysAgo(6) },
    ],
  },
];
