import { CUSTOMERS } from "./customers.seed";
import { daysAgo } from "./id.util";
import { MockNotification } from "./types";

const c = CUSTOMERS;

/** In-app notification inbox items. `userId: null` entries are broadcasts (flash sales, drops) shown to everyone. */
export const NOTIFICATIONS: MockNotification[] = [
  {
    id: "notif_001",
    userId: c[0].id,
    type: "order_update",
    title: "Your order has shipped",
    message: "Order #SVN-10432 (V2 Hoodie — Cloud, size M) is on its way via TCS. Estimated delivery in 2-3 days.",
    read: false,
    createdAt: daysAgo(0),
  },
  {
    id: "notif_002",
    userId: c[0].id,
    type: "review_reminder",
    title: "How's the fit?",
    message: "You've had your Overdye Tee — Charcoal for a week. Leave a review and get 200 points toward your next order.",
    read: false,
    createdAt: daysAgo(1),
  },
  {
    id: "notif_003",
    userId: c[1].id,
    type: "order_update",
    title: "Order confirmed",
    message: "Order #SVN-10417 confirmed. We're packing it now — you'll get a shipping notification within 24 hours.",
    read: true,
    createdAt: daysAgo(2),
  },
  {
    id: "notif_004",
    userId: c[2].id,
    type: "order_update",
    title: "Out for delivery",
    message: "Order #SVN-10390 is out for delivery today in Islamabad. Keep your phone nearby for the rider's call.",
    read: true,
    createdAt: daysAgo(3),
  },
  {
    id: "notif_005",
    userId: null,
    type: "promotion",
    title: "VOL. 07 just dropped",
    message: "The new drop is live — limited run, no restock. 10% off your first piece with code DROP07.",
    read: false,
    createdAt: daysAgo(4),
  },
  {
    id: "notif_006",
    userId: c[4].id,
    type: "order_update",
    title: "Delivered",
    message: "Order #SVN-10355 was delivered. Thanks for shopping Seventh — tag us @seventh.pk in your fit pic.",
    read: true,
    createdAt: daysAgo(6),
  },
  {
    id: "notif_007",
    userId: null,
    type: "promotion",
    title: "Flash sale — 24 hours only",
    message: "Flat 15% off outerwear, tonight only. Ends midnight.",
    read: false,
    createdAt: daysAgo(7),
  },
  {
    id: "notif_008",
    userId: c[6].id,
    type: "system",
    title: "Welcome to Seventh",
    message: "Thanks for creating an account. Here's 10% off your first order: WELCOME10.",
    read: true,
    createdAt: daysAgo(165),
  },
  {
    id: "notif_009",
    userId: c[3].id,
    type: "order_update",
    title: "Payment failed",
    message: "Your JazzCash payment for order #SVN-10288 didn't go through. Retry payment or switch to Cash on Delivery.",
    read: false,
    createdAt: daysAgo(9),
  },
  {
    id: "notif_010",
    userId: c[7].id,
    type: "review_reminder",
    title: "Rate your recent pickup",
    message: "How was the Cargo Pant — Olive? Your review helps other customers pick the right size.",
    read: false,
    createdAt: daysAgo(10),
  },
  {
    id: "notif_011",
    userId: null,
    type: "promotion",
    title: "Free shipping weekend",
    message: "No minimum. Free shipping on every order this Saturday and Sunday.",
    read: true,
    createdAt: daysAgo(12),
  },
  {
    id: "notif_012",
    userId: c[9].id,
    type: "order_update",
    title: "Order shipped",
    message: "Order #SVN-10201 (Coach Jacket — Ink) has shipped via Leopards Courier.",
    read: true,
    createdAt: daysAgo(14),
  },
  {
    id: "notif_013",
    userId: c[2].id,
    type: "system",
    title: "New address saved",
    message: "We've saved your new delivery address in DHA Phase 3, Islamabad.",
    read: true,
    createdAt: daysAgo(20),
  },
  {
    id: "notif_014",
    userId: c[10].id,
    type: "order_update",
    title: "Order confirmed",
    message: "Order #SVN-10156 confirmed. Cash on Delivery selected — have exact change ready if possible.",
    read: true,
    createdAt: daysAgo(25),
  },
];
