import { daysAgo, daysFromNow } from "./id.util";
import { MockPromotion } from "./types";

/** Coupon/campaign data for the storefront promo field and the admin "Promotions" screen (coupons, flash sales, banners — PRD 4.2). */
export const PROMOTIONS: MockPromotion[] = [
  {
    id: "promo_001",
    code: "DROP07",
    description: "10% off your first piece from the VOL. 07 drop.",
    discountType: "percentage",
    discountValue: 10,
    validFrom: daysAgo(4),
    validUntil: daysFromNow(10),
    usageCount: 214,
    usageLimit: 1000,
    active: true,
  },
  {
    id: "promo_002",
    code: "WELCOME10",
    description: "10% off for new accounts, first order only.",
    discountType: "percentage",
    discountValue: 10,
    validFrom: daysAgo(365),
    validUntil: daysFromNow(365),
    usageCount: 1893,
    usageLimit: 0,
    active: true,
  },
  {
    id: "promo_003",
    code: "FLASH15",
    description: "Flat 15% off outerwear — 24 hour flash sale.",
    discountType: "percentage",
    discountValue: 15,
    validFrom: daysAgo(7),
    validUntil: daysAgo(6),
    usageCount: 356,
    usageLimit: 500,
    active: false,
  },
  {
    id: "promo_004",
    code: "FREESHIP",
    description: "Free standard shipping, no minimum order.",
    discountType: "free_shipping",
    discountValue: 0,
    validFrom: daysAgo(12),
    validUntil: daysAgo(10),
    usageCount: 742,
    usageLimit: 0,
    active: false,
  },
  {
    id: "promo_005",
    code: "SAVE500",
    description: "Flat Rs 500 off orders over Rs 4000.",
    discountType: "fixed",
    discountValue: 500,
    validFrom: daysAgo(20),
    validUntil: daysFromNow(5),
    usageCount: 88,
    usageLimit: 300,
    active: true,
  },
  {
    id: "promo_006",
    code: "EIDSALE",
    description: "Eid collection sale — 20% off select styles.",
    discountType: "percentage",
    discountValue: 20,
    validFrom: daysFromNow(30),
    validUntil: daysFromNow(37),
    usageCount: 0,
    usageLimit: 2000,
    active: false,
  },
];
